set(NS3_PATH ../NS3/build)
set(NS3_VER 3.27)
set(NS3_BUILDTYPE debug)

set(NS3_MODULES
    aodv
    applications
    bridge
    config-store
    core
    csma-layout
    csma
    dsdv
    emu
    energy
    flow-monitor
    internet
    lte
    mesh
    mobility
    mpi
    netanim
    network
    nix-vector-routing
    olsr
    point-to-point-layout
    point-to-point
    propagation
    spectrum
    stats
    tap-bridge
    template
    test
    tools
    topology-read
    uan
    virtual-net-device
    visualizer
    wifi
    wimax
        )

set(NS3_LIBRARIES )

#Check if each of NS3 modules exist on NS3_PATH/lib
foreach(module ${NS3_MODULES})
    set(ns3-${module} "libns${NS3_VER}-${module}-${NS3_BUILDTYPE}.so")
    get_filename_component(ABS_PATH "${NS3_PATH}/lib/${ns3-${module}}" ABSOLUTE)
    if(EXISTS ${ABS_PATH})
        list(APPEND NS3_LIBRARIES ${ns3-${module}})
    endif()
endforeach()

#Include header folder to include path (-INS3_PATH)
include_directories(${NS3_PATH})

#Include libraries folder to link path (-LNS3_PATH/lib)
link_directories(${NS3_PATH}/lib)

#Read definitions file generated by the CMake script of NS3 project (https://github.com/Gabrielcarvfer/NS3)
file(READ ${NS3_PATH}/ns3/ns3-definitions NS3_DEFINITIONS)
foreach(definition ${NS3_DEFINITIONS})
    add_definitions(-D${definition})
endforeach()